config/routes.rb
Rails.application.routes.draw do

  get 'welcome/request_w', as: 'weather_request'

  get 'welcome/response_w', as: 'weather_response'

  get 'welcome/set_key', as: 'weather_key'

  post 'welcome/submit_key', as: 'submit_key'

  root "welcome#request_w"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def request
    @s = 2


  end


  def response


  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  require 'rubygems'
  require 'json'


  def set_key

  end

  def submit_key
    $api_key = params[:api_key][:api_key]
    redirect_to root_path
  end


  def request_w


  end

  def response_w
    @city = params[:request][:city]
    @country = params[:request][:state]
    @temp  = Weathy.weather_by_city(@city,@country)



    #@temp = JSON.parse(@res)


  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeathyRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WeathyRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/pages/request.html.haml
=@p

app/views/welcome/request_w.html.haml
-if $api_key.nil?
  %h1
    Please, set your API key
    =link_to weather_key_path do
      here
-else
  %h1 Your API Key:
  %h2
    =$api_key


  = simple_form_for(:request, :url =>weather_response_path, :html => { :method => 'GET' }) do |f|
    = f.input :city,  label: "City"
    = f.input :state,  label: "Country/State"
    -#= f.input :choose_country,  label: "eCountry/State"
    = f.button :submit, "Get Weather"

app/views/welcome/response_w.html.haml
%h1 Request:
%h2
  #{@city}, #{@country}


%h1 Response:
-@temp.each do |key, array|
  %h3
    #{key}: #{array}


=link_to weather_request_path do
  %h3 Submit again

app/views/welcome/set_key.html.haml
= simple_form_for(:api_key, :url =>submit_key_path) do |f|
  = f.input :api_key,  label: "API key"
  = f.button :submit, "Set"